# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e553a6822b60fc9b9196ae670f6ecc9c94329d84c263e91344a6e3a8e5c394eaeebf678bb0be0d79059687389f4073a5bf52f41d77acbae4c2fd92a59f272a

test:
  secret_key_base: a64f0e47fa625cbcb0525ba7cfd4192b1b9c412608e14dbb127c9f585784cffe8840c17f7e0491e506c009136d021302dfe4f07fe073f57fd298571f5eef3a4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
